global using Materal.Abstractions;
global using Materal.TTA.Common;
global using Materal.Utils.Enums;
global using Materal.Utils.Extensions;
global using Materal.Utils.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using System.Linq.Expressions;
